# Generated by Django 5.1.4 on 2024-12-14 15:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_newspage_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="reserve_players",
            field=wagtail.fields.StreamField(
                [("player", 0)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("team.ClubMember",),
                        {"required": False},
                    )
                },
            ),
        ),
    ]
