# Generated by Django 5.1.4 on 2024-12-14 16:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_newspage_reserve_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="players",
            field=wagtail.fields.StreamField(
                [("player", 0)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("team.ClubMember",),
                        {"max_length": 11, "min_length": 11, "required": False},
                    )
                },
            ),
        ),
    ]
