# Generated by Django 5.1.3 on 2024-12-02 20:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teampage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("images_with_text", 5)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageBlock", [], {}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("name_caption", 2), ("function", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                },
            ),
        ),
    ]
