# Generated by Django 5.1.3 on 2024-12-03 20:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0004_alter_teampage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teampage",
            name="body",
            field=wagtail.fields.StreamField(
                [("parts", 5)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.images.blocks.ImageBlock", [], {}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 1),
                                ("first_name", 0),
                                ("last_name", 0),
                                ("function", 2),
                            ]
                        ],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("cap_images", 4)]],
                        {},
                    ),
                },
            ),
        ),
    ]
