# Generated by Django 5.1.4 on 2024-12-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_alter_teampage_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20, null=True)),
                ("function", models.CharField(max_length=20, null=True)),
                (
                    "player_number",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "foto",
                    models.ForeignKey(
                        help_text="Sponsor logo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
    ]
