# Generated by Django 5.1.4 on 2024-12-08 11:02

import team.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0006_clubmember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubmember",
            options={"ordering": ["last_name"]},
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="first_name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="teampage",
            name="body",
            field=wagtail.fields.StreamField(
                [("parts", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (team.models.ClubMember,),
                        {},
                    ),
                    2: ("wagtail.blocks.ListBlock", (1,), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("cap_images", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
