# Generated by Django 5.1.4 on 2024-12-08 15:40

import team.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0007_alter_clubmember_options_alter_clubmember_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teampage",
            name="body",
            field=wagtail.fields.StreamField(
                [("parts", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (team.models.ClubMember,),
                        {},
                    ),
                    2: ("wagtail.blocks.ListBlock", (1,), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("members", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
