# Generated by Django 5.1.4 on 2024-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0009_alter_clubmember_player_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="teampage",
            name="menu_order",
            field=models.IntegerField(default=0, help_text="Setup custom menu order"),
        ),
    ]
