# Generated by Django 5.1.4 on 2024-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_result_the_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulepage",
            name="menu_order",
            field=models.IntegerField(default=0, help_text="Setup custom menu order"),
        ),
    ]
