# Generated by Django 5.1.4 on 2024-12-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
