# Generated by Django 5.1.4 on 2024-12-09 18:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_sponsor_sort_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="sponsor",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="sponsor",
            name="group",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="TheSponsor",
                to="home.sponsors",
            ),
        ),
    ]
