# Generated by Django 5.1.4 on 2024-12-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_sponsors_alter_sponsor_options_sponsor_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsor",
            name="group",
        ),
        migrations.AlterModelOptions(
            name="sponsor",
            options={"ordering": ["position"]},
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="sponsor",
            name="position",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="Sponsors",
        ),
    ]
